import { Providers } from '@/components/client/Providers/Providers.client';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='flex min-h-screen flex-col px-8 py-16'>
          <div>
            <Providers>{children}</Providers>
          </div>
        </main>
      </body>
    </html>
  );
}
